import 'package:flutter/material.dart';
import 'package:widget_of_the_day/features/widgets_of_the_day/widgets_of_the_day.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Widget Of The Day',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Color(0xFF4F46E5)),
        useMaterial3: false,
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF4F46E5), // Indigo
          foregroundColor: Colors.white,
          centerTitle: true,
          elevation: 0,
          titleTextStyle: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.w600,
            color: Colors.white,
          ),
        ),
      ),
      // home: const Day01ContainerWidget(),
      // home: const Day02ExpandedWidget(),
      // home: const Day03ColumnWidget(),
      // home: const Day03RowWidget(),
      // home:  Day04ListViewWidget(),
      // home: const Day05ClipRRectWidget(),
      // home: const Day06ImageAssetWidget(),
      // home: const Day07GridViewWidget(),
      // home: const Day08GestureDetectorWidget(),
      // home: const Day09BottomNavBarWidget(),
      // home: const Day10AppBarWidget(),
      // home: const Day11DrawerWidget(),
      // home: const Day12SliverAppBarWidget(),
      // home: const Day13TabBarWidget(),
      // home: const Day14AnimatedContainerWidget(),
      // home: const Day15MediaQueryWidget(),
      // home: Day16AlertDialogWidget(),
      // home: Day17TextStyleWidget(),
      // home: Day18RichTextWidget(),
      // home: const Day19TimerWidget(),
      // home: const Day20PageViewWidget(),
      // home: const Day21StackWidget(),
      // home: const Day22TextFieldWidget(),
      // home: const Day23AnimatedIconWidget(),
      // home: const Day24SliderWidget(),
      // home: const Day25DatePickerWidget(),
      // home: const Day26TimePickerWidget(),
      // home: const Day27WheelTimePickerWidget(),
      // home: const Day28LinearGradientWidget(),
      // home: const Day29ElevatedButtonAndOutlinedButtonWidget(),
      // home: const Day30FloatingActionButtonWidget(),
      // home: const Day31NavigatorWidget(),
      // home: const Day32CardWidget(),
      // home: const Day33ClipperWidget(),
      // home: const Day34RawMaterialButtonWidget(),
      // home: const Day35RotatedBoxWidget(),
      // home: const Day36TransformWidget(),
      // home: const Day37PositionedWidget(),
      // home: const Day38IconButtonWidget(),
      // home: const Day39CustomPaintWidget(),
      // home: const Day40ClipOvalWidget(),
      // home: const Day41ClipRRectWidget(),
      // home: const Day42ClipRectWidget(),
      // home: const Day43ClipPathWidget(),
      // home: const Day44RadialAndSweepGradientWidget(),
      // home: const Day45StatefulWidget(number: 0),
      // home: const Day46TableWidget(),
      // home: const Day47DataTableWidget(),
      // home: const Day48PlaceholderWidget(),
      // home: const Day49GestureInkWellWidget(),
      // home: const Day50MaterialWidget(),
      // home: const Day51SwitchesWidget(),
      // home: const Day52DropdownAndPopupMenuWidget(),
      // home: const Day53HeroAnimationWidget(),
      // home: const Day54AboutDialogWidget(),
      // home: const Day55StepperWidget(),
      // home: const Day56FittedBoxWidget(),
      // home: const Day57ShowSearchWidget(),
      // home: const Day58AdaptiveWidget(),
      // home: const Day59ScrollbarWidget(),
      // home: const Day60ChoiceChipWidget(),
      // home: const Day61WrapWidget(),
      // home: const Day62ExpansionTileWidget(),
      // home: const Day63RangeSliderWidget(),
      // home: const Day64ShowModalBottomSheetWidget(),
      // home: const Day65AnimatedCrossFadeWidget(),
      // home: const Day66FlexibleWidget(),
      // home: const Day67SpacerWidget(),
      // home: const Day68GridPaperWidget(),
      // home: const Day69InteractiveViewerWidget(),
      // home: const Day70CheckboxListTileWidget(),
      // home: const Day71SelectableTextWidget(),
      // home: const Day72AnimatedPaddingWidget(),
      // home: const Day73RefreshIndicatorWidget(),
      // home: const Day74ImageFilteredWidget(),
      // home: const Day75AspectRatioWidget(),
      // home: const Day76ToggleButtonsWidget(),
      // home: const Day77PhysicalModelWidget(),
      // home: const Day78AlignWidget(),
      // home: const Day79SafeAreaWidget(),
      // home: const Day80PageRouteBuilderWidget(),
      // home: const Day81DraggableWidget(),
      // home: const Day82BackdropFilterWidget(),
      // home: const Day83ReorderableListViewWidget(),
      // home: const Day84FadeTransitionWidget(),
      // home: const Day85CircleAvatarWidget(),
      // home: const Day86TooltipWidget(),
      // home: const Day87VisibilityWidget(),
      // home: const Day88IndexedStackWidget(),
      // home: const Day89Navigator2Widget(),
      // home: const Day90NullAwareOperatorsWidget(),
      // home: const Day91CascadeOperatorWidget(),
      // home: const Day92InheritedWidget(),
      // home: const Day93FractionallySizedBox(),
      // home: const Day94ConstrainedBox(),
      // home: const Day95CupertinoSearchTextField(),
      // home: const Day96StatefulBuilder(),
      // home: const Day97LayoutBuilder(),
      // home: const Day98OrientationBuilder(),
      // home: const Day99PlatformDetect(),
      // home: const Day100FutureBuilder(),
      // home: const Day101StreamBuilder(),
      // home: const Day102ChangeNotifier(),
      // home: const Day103ValueNotifier(),
      // home: const Day104InheritedNotifier(),
      // home: const Day105Listener(),
      // home: const Day106Builder(),
      // home: const Day107PageViewBuilder(),
      // home: const Day108AnimatedBuilder(),
      // home: const Day109SnackBar(),
      // home: const Day110SizedBox(),
      // home: const Day111IntrinsicWidgets(),
      // home: const Day112OverflowBox(),
      // home: const Day113UnconstrainedBox(),
      // home: const Day114LimitedBox(),
      // home: const Day115Baseline(),
      // home: const Day116Opacity(),
      // home: const Day117ColorFiltered(),
      // home: const Day118ShaderMask(),
      // home: const Day119DecoratedBox(),
      // home: const Day120FractionalTranslation(),
      // home: const Day121CustomMultiChildLayout(),
      // home: const Day122TextInputFormatter(),
      // home: const Day123AutofillGroup(),
      // home: const Day124EditableText(),
      // home: const Day125DefaultTextStyle(),
      // home: const Day126SliverListAndSliverGrid(),
      // home: const Day127SliverPersistentHeader(),
      // home: const Day128SliverFillRemaining(),
      // home: const Day129NestedScrollView(),
      // home: const Day130ScrollController(),
      // home: const Day131NotificationListener(),
      // home: const Day132Semantics(),
      // home: const Day133ExcludeAndMergeSemantics(),
      home: const Day134FocusNode(),
    );
  }
}
